# Generated by Django 4.0.2 on 2022-02-27 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaryApp', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
